use polaris_core::pack_state::PackSummary;
use polaris_core::status::{ConceptStatus, PhaseCount, StatusSnapshot};
use serde::Serialize;
use ts_rs::TS;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
pub struct CommandError {
    pub code: String,
    pub message: String,
    pub retryable: bool,
}

impl std::fmt::Display for CommandError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for CommandError {}

impl CommandError {
    pub fn core(error: impl std::fmt::Display) -> Self {
        Self {
            code: "core_error".to_owned(),
            message: error.to_string(),
            retryable: false,
        }
    }

    pub fn state(message: impl Into<String>) -> Self {
        Self {
            code: "state_unavailable".to_owned(),
            message: message.into(),
            retryable: true,
        }
    }
}

pub fn generated_typescript_contracts() -> String {
    let config = ts_rs::Config::default();
    let declarations = [
        PackSummary::decl(&config),
        PhaseCount::decl(&config),
        ConceptStatus::decl(&config),
        StatusSnapshot::decl(&config),
        CommandError::decl(&config),
    ];
    format!(
        "// @generated by polaris-desktop Rust DTOs. Do not edit by hand.\n{}\n",
        declarations
            .into_iter()
            .map(|declaration| format!("export {declaration}"))
            .collect::<Vec<_>>()
            .join("\n")
    )
}
