import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import axe from "axe-core";
import { beforeEach, describe, expect, it, vi } from "vitest";

import { previewSettingsWorkspace } from "../lib/settingsPreview";
import { SettingsPage } from "./SettingsPage";

const commands = vi.hoisted(() => ({ acknowledgeDatabasePath: vi.fn(), exportProfile: vi.fn(), getLifecycleStatus: vi.fn(), getSettingsWorkspace: vi.fn(), resetProfile: vi.fn(), selectDatabasePath: vi.fn(), submitProfileMeasurement: vi.fn(), updateAiProfile: vi.fn(), updateProfileSettings: vi.fn() }));
vi.mock("../lib/commands", async (importOriginal) => ({ ...await importOriginal<typeof import("../lib/commands")>(), ...commands }));
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><SettingsPage /></QueryClientProvider>); }

describe("SettingsPage", () => {
  beforeEach(() => { vi.clearAllMocks(); commands.getLifecycleStatus.mockResolvedValue({ database_path: "C:\\Polaris\\polaris.sqlite", database_source: "saved", database_path_acknowledged: true, startup_status: "ready", startup_message: "数据库完整且版本受支持。", schema_version: 9, upgrade_required: false, pre_upgrade_backup: null, previous_run_incomplete: false, recovered_background_jobs: [], pending_background_jobs: [], config_warning: null, startup_enabled: false, fast_api_key_configured: false, strong_api_key_configured: false, embed_api_key_configured: false }); commands.getSettingsWorkspace.mockResolvedValue(previewSettingsWorkspace()); commands.updateProfileSettings.mockResolvedValue({ effect: "profile_settings_updated", message: "已保存" }); commands.updateAiProfile.mockResolvedValue({ effect: "ai_profile_updated", message: "已保存" }); commands.resetProfile.mockResolvedValue({ effect: "profile_reset", message: "已清除" }); commands.selectDatabasePath.mockResolvedValue({ effect: "database_path_changed", message: "已切换" }); });
  it("shows real privacy degradation and writes profile controls", async () => { renderPage(); expect(await screen.findByRole("heading", { name: "控制画像、AI 与数据边界。" })).toBeVisible(); expect(screen.getByText("POLARIS_TIER0_ONLY=1")).toBeVisible(); fireEvent.click(screen.getByRole("checkbox", { name: /启用本地画像/ })); await waitFor(() => { expect(commands.updateProfileSettings).toHaveBeenCalled(); }); expect(commands.updateProfileSettings.mock.calls[0]?.[0]).toEqual(expect.objectContaining({ enabled: false })); });
  it("has no detectable structural accessibility violations", async () => { const { container } = renderPage(); await screen.findByRole("heading", { name: "控制画像、AI 与数据边界。" }); const result = await axe.run(container, { rules: { "color-contrast": { enabled: false } } }); expect(result.violations).toEqual([]); });
  it("keeps recovery controls available when the engine cannot open the database", async () => { commands.getLifecycleStatus.mockResolvedValue({ database_path: "C:\\locked.sqlite", database_source: "saved", database_path_acknowledged: true, startup_status: "locked", startup_message: "数据库正被其他进程锁定。", schema_version: null, upgrade_required: false, pre_upgrade_backup: null, previous_run_incomplete: true, recovered_background_jobs: ["backup"], pending_background_jobs: ["backup"], config_warning: null, startup_enabled: false, fast_api_key_configured: false, strong_api_key_configured: false, embed_api_key_configured: false }); renderPage(); expect(await screen.findByRole("heading", { name: "学习数据没有被改动。" })).toBeVisible(); fireEvent.change(screen.getByLabelText(/改选一个现有数据库/), { target: { value: "C:\\new.sqlite" } }); fireEvent.click(screen.getByRole("button", { name: "检查并使用此路径" })); await waitFor(() => { expect(commands.selectDatabasePath.mock.calls[0]?.[0]).toEqual({ path: "C:\\new.sqlite" }); }); });
});
