// @generated by polaris-desktop Rust DTOs. Do not edit by hand.
export type PackSummary = { id: string, title: string, concept_count: number, active: boolean, theta_mode: string, };
export type PhaseCount = { phase: string, count: number, };
export type ConceptStatus = { concept_id: string, name: string, retrieval: number | null, p_known: number, calib_gap: number, phase: string, phase_label: string, phase_summary: string, };
export type StatusSnapshot = { generated_at: string, current_pack: string | null, theta_mode: string | null, packs: Array<PackSummary>, due_today: number, phase_counts: Array<PhaseCount>, concepts: Array<ConceptStatus>, };
export type PackSwitchReceipt = { active_pack: string, theta_mode: string, };
export type NotificationPolicy = { state_gate_passed: boolean, dominant_state: string | null, suppress_non_error: boolean, };
export type TodayAction = { id: string, kind: string, title: string, detail: string, route: string | null, concept_id: string | null, expected_success: number | null, };
export type TodaySignal = { claim: string, confidence: number, suggested_action: string | null, };
export type TodaySnapshot = { generated_at: string, current_pack: string | null, theta_mode: string | null, packs: Array<PackSummary>, top_signal: TodaySignal | null, actions: Array<TodayAction>, notification_policy: NotificationPolicy, };
export type WindowModeReceipt = { mode: string, };
export type NotificationReceipt = { emitted: boolean, suppressed_by_flow: boolean, };
export type CommandError = { code: string, message: string, retryable: boolean, };
