// @generated by polaris-desktop Rust DTOs. Do not edit by hand.
export type PackSummary = { id: string, title: string, concept_count: number, active: boolean, theta_mode: string, };
export type PhaseCount = { phase: string, count: number, };
export type ConceptStatus = { concept_id: string, name: string, retrieval: number | null, p_known: number, calib_gap: number, phase: string, phase_label: string, phase_summary: string, };
export type StatusSnapshot = { generated_at: string, current_pack: string | null, theta_mode: string | null, packs: Array<PackSummary>, due_today: number, phase_counts: Array<PhaseCount>, concepts: Array<ConceptStatus>, };
export type CommandError = { code: string, message: string, retryable: boolean, };
